### ISSUE TITLE
CUBE: visual issues

### ISSUE THREAD

**Issue by kas1e** [ptitSeb/gl4es#138]
Hi!

While experiment with Cube's speed over gl4es found that it has visuall issues. There are some strange diagonal lines in the boxes, check this out:

MiniGL build:

http://kas1e.mikendezign.com/aos4/gl4es/games/cube/cube_minigl.jpg

GL4ES build:

http://kas1e.mikendezign.com/aos4/gl4es/games/cube/cube_gl4es.jpg

See, diagonal lines in the boxes? 

I tried even with LIBGL_BATCH 0, and with any other value: still the same.

Maybe that can be reasons for that big slow-down in compare even when libgl_batch is used, maybe some vertexes just didn't connect correctly together and "batch" didn't work very well because of that?

**Comment by ptitSeb** [comment]
That is probably an artefact with the surface drawn as line instead of filled triangle. gl4es is supposed to handled that, but it seems that there is some wrong cases. I'll analyse that.

**Comment by ptitSeb** [comment]
Ok, should be fixed now

(FYI, at start, on 640x480 on teh pandora, my framerate is around 50fps to 60fps on GLES1.1 backend but only around 20~25fps on GLES2, with a few graphics artefacts. I think it's using GL_PLANES but I need to analyse a bit more what is happening).

**Comment by kas1e** [comment]
Thanks, will check

And yep, there surely something wrong with speed. Remember we have that kind of issue with Gorynlich: gles1.1 give 60fps, and gles2 20fps. Will be cool if we can find the roots :) Thanks !

**Comment by ptitSeb** [comment]
I made a trace.

Nothing really suspicious pops out except:
* There are *A LOT* of drawing call! Using GL_BATCH may help, I have to analyse that.
* There a glReadPixels at the end of each frame: this tend to kills the performances on GLES hardware. Also, the read is on GL_DEPTH_COMPONENT, wich is not supported on GLES hardware (maybe it is on AmigaOS): this make shooting impossible, like if there always was an invisible wall just in front of you.

**Comment by kas1e** [comment]
> There are A LOT of drawing call! Using GL_BATCH may help, I have to analyze that.

Yeah, and with GL_BATCH its a bit faster than before, for sure. But still, lots slower as expected: I have on my hardware also just 35 fps at the beginning which drops in few seconds to 20. With MiniGL it starts as 40 and never drops less than 35. 

> There a glReadPixels at the end of each frame: this tend to kills the performances on GLES hardware.

But then it should be the same for GLES1 too? And is it expected to kill it that much?

> Also, the read is on GL_DEPTH_COMPONENT, wich is not supported on GLES hardware (maybe it is on AmigaOS): this make shooting impossible, like if there always was an invisible wall just in front of you.

MiniGL also has a problem with glReadPixels with GL_DEPTH_COMPONENT back in past. It was that game uses glReadPixel() function for founding the chords with refers to Z-component, which our warp3d/minigl cant handle at all and result was bugs like "you fire in air like to the wall", "fire from grenade kill yourself", "you cant fire to anyone" and so on. So, after some annoing on forums i found one man with nickname "Tempest", who replace read_depth function to make it works not with glReadPixel + z_buffer, but by SANE method (sin/cos/etc), and as result, we have fully working game.

And that is one I use for tests which has that big speed drop. 

If you in interest i can share the changes we do (there was a little) so you can make it for Pandora too.

**Comment by kas1e** [comment]
I was lucky enough and found cube1_diff I had. It applied in 2010 on top of the 2005 version of cube1 (so probably last one). There is: http://kas1e.mikendezign.com/aos4/gl4es/games/cube/cube1_diff.txt

I also have diff for assault_cube (so to fix the same issue) but need to find that one too. I still can't make it works by some reason on my side (have a black screen), need to understand wtf... But that later.

So after you will apply that diff, no glReadPixel will be used, and so, why speed drop then .. And only on GLES2 hardware, not GLES1.  Same as happens with Gorynlich. There should be something common ..

**Comment by ptitSeb** [comment]
I don't really explain why the speed drop is more in GLES2 than with GLES1.1 backend. With BATCH mode, there are a bit less drawing call, but still quite a lot... And almost no VBO, so no speedup here.
I don't see much stuff. The glReadPixel alone is not a big issue, and removing it doesn't change speed significantly.

The GL_DEPTH_COMPONENT reading, yeah, if you have the code, that could be nice. I tried to plug in the code from Intel version, that was ported to GLES, but it's not satisfying, it doesn't "aim correctly" all the time...

**Comment by kas1e** [comment]
Yep, see the diff in the previous post.

If I understand right, be it GLES1 or GLES2  that in general the same "GLES" hardware, so usually, if something can work over GLES1 or GLES2 (i.e. the same code), speed should be the same? 

For example, if do trace log of GLES1 running, what will be there different in compare with GLEs2 ?

**Comment by kas1e** [comment]
Maybe with Gorynlich and Cube1, we have some scenarios when Batching didn't work well? For GLES1 version of GL4ES we use the same "batching" code, right? And on GLES1 it's faster even without batching?

**Comment by ptitSeb** [comment]
Thanks for the patch. I applied it and it seems to work fine (still needs more testing).

Yes, GLES1.1 is always (well, most of the time) faster than GLES2. That's normal, fixed pipeline is faster.

Clearly, in GLES1.1 or GLES2, it's the GLES driver that take most time.
